export const COUNTRIES = [
    { code: "AF", name: "Afghanistan" },
    { code: "AL", name: "Albania" },
    { code: "DZ", name: "Algeria" },
    { code: "AR", name: "Argentina" },
    { code: "AU", name: "Australia" },
    { code: "AT", name: "Austria" },
    { code: "BD", name: "Bangladesh" },
    { code: "BE", name: "Belgium" },
    { code: "BR", name: "Brazil" },
    { code: "BG", name: "Bulgaria" },
    { code: "CA", name: "Canada" },
    { code: "CL", name: "Chile" },
    { code: "CN", name: "China" },
    { code: "CO", name: "Colombia" },
    { code: "HR", name: "Croatia" },
    { code: "CZ", name: "Czech Republic" },
    { code: "DK", name: "Denmark" },
    { code: "EG", name: "Egypt" },
    { code: "FI", name: "Finland" },
    { code: "FR", name: "France" },
    { code: "DE", name: "Germany" },
    { code: "GR", name: "Greece" },
    { code: "HK", name: "Hong Kong" },
    { code: "HU", name: "Hungary" },
    { code: "IN", name: "India" },
    { code: "ID", name: "Indonesia" },
    { code: "IE", name: "Ireland" },
    { code: "IL", name: "Israel" },
    { code: "IT", name: "Italy" },
    { code: "JP", name: "Japan" },
    { code: "KE", name: "Kenya" },
    { code: "MY", name: "Malaysia" },
    { code: "MX", name: "Mexico" },
    { code: "MA", name: "Morocco" },
    { code: "NL", name: "Netherlands" },
    { code: "NZ", name: "New Zealand" },
    { code: "NG", name: "Nigeria" },
    { code: "NO", name: "Norway" },
    { code: "PK", name: "Pakistan" },
    { code: "PE", name: "Peru" },
    { code: "PH", name: "Philippines" },
    { code: "PL", name: "Poland" },
    { code: "PT", name: "Portugal" },
    { code: "RO", name: "Romania" },
    { code: "RU", name: "Russia" },
    { code: "SA", name: "Saudi Arabia" },
    { code: "SG", name: "Singapore" },
    { code: "ZA", name: "South Africa" },
    { code: "KR", name: "South Korea" },
    { code: "ES", name: "Spain" },
    { code: "SE", name: "Sweden" },
    { code: "CH", name: "Switzerland" },
    { code: "TH", name: "Thailand" },
    { code: "TR", name: "Turkey" },
    { code: "UA", name: "Ukraine" },
    { code: "AE", name: "United Arab Emirates" },
    { code: "GB", name: "United Kingdom" },
    { code: "US", name: "United States" },
    { code: "VN", name: "Vietnam" }
];

export const CATEGORIES = [
    // Electronics
    { value: "electronics", label: "Electronics" },
    { value: "smartphones", label: "Smartphones" },
    { value: "laptops", label: "Laptops" },
    { value: "desktops", label: "Desktops" },
    { value: "tablets", label: "Tablets" },
    { value: "smartwatches", label: "Smartwatches" },
    { value: "cameras", label: "Cameras" },
    { value: "headphones", label: "Headphones" },
    { value: "speakers", label: "Speakers" },
    { value: "gaming-consoles", label: "Gaming Consoles" },
    { value: "video-games", label: "Video Games" },
    { value: "computer-accessories", label: "Computer Accessories" },
    { value: "networking", label: "Networking Devices" },
    { value: "tv-home-theater", label: "TV & Home Theater" },

    // Fashion
    { value: "fashion", label: "Fashion" },
    { value: "mens-clothing", label: "Men's Clothing" },
    { value: "womens-clothing", label: "Women's Clothing" },
    { value: "kids-clothing", label: "Kids' Clothing" },
    { value: "shoes", label: "Shoes" },
    { value: "bags", label: "Bags" },
    { value: "jewelry", label: "Jewelry" },
    { value: "watches", label: "Watches" },
    { value: "sunglasses", label: "Sunglasses" },
    { value: "activewear", label: "Activewear" },

    // Home & Living
    { value: "home-living", label: "Home & Living" },
    { value: "furniture", label: "Furniture" },
    { value: "home-decor", label: "Home Decor" },
    { value: "kitchen-dining", label: "Kitchen & Dining" },
    { value: "bedding", label: "Bedding" },
    { value: "bath", label: "Bath" },
    { value: "lighting", label: "Lighting" },
    { value: "storage-organization", label: "Storage & Organization" },
    { value: "appliances", label: "Home Appliances" },

    // Beauty & Health
    { value: "beauty-health", label: "Beauty & Health" },
    { value: "skincare", label: "Skincare" },
    { value: "haircare", label: "Haircare" },
    { value: "makeup", label: "Makeup" },
    { value: "fragrances", label: "Fragrances" },
    { value: "personal-care", label: "Personal Care" },
    { value: "health-supplements", label: "Health Supplements" },
    { value: "medical-supplies", label: "Medical Supplies" },

    // Grocery
    { value: "grocery", label: "Grocery" },
    { value: "beverages", label: "Beverages" },
    { value: "snacks", label: "Snacks" },
    { value: "organic-food", label: "Organic Food" },
    { value: "frozen-food", label: "Frozen Food" },
    { value: "fresh-produce", label: "Fresh Produce" },
    { value: "bakery", label: "Bakery" },

    // Sports & Outdoors
    { value: "sports-outdoors", label: "Sports & Outdoors" },
    { value: "fitness-equipment", label: "Fitness Equipment" },
    { value: "outdoor-recreation", label: "Outdoor Recreation" },
    { value: "camping-hiking", label: "Camping & Hiking" },
    { value: "cycling", label: "Cycling" },
    { value: "team-sports", label: "Team Sports" },
    { value: "water-sports", label: "Water Sports" },

    // Automotive
    { value: "automotive", label: "Automotive" },
    { value: "car-accessories", label: "Car Accessories" },
    { value: "car-parts", label: "Car Parts" },
    { value: "motorcycle-accessories", label: "Motorcycle Accessories" },
    { value: "tools-equipment", label: "Tools & Equipment" },

    // Baby & Kids
    { value: "baby-kids", label: "Baby & Kids" },
    { value: "baby-clothing", label: "Baby Clothing" },
    { value: "baby-gear", label: "Baby Gear" },
    { value: "toys-games", label: "Toys & Games" },
    { value: "educational-toys", label: "Educational Toys" },

    // Office & Stationery
    { value: "office-supplies", label: "Office Supplies" },
    { value: "stationery", label: "Stationery" },
    { value: "printers", label: "Printers" },
    { value: "office-furniture", label: "Office Furniture" },

    // Books & Media
    { value: "books-media", label: "Books & Media" },
    { value: "books", label: "Books" },
    { value: "ebooks", label: "eBooks" },
    { value: "magazines", label: "Magazines" },
    { value: "music", label: "Music" },
    { value: "movies", label: "Movies" },

    // Digital Products
    { value: "digital-products", label: "Digital Products" },
    { value: "software", label: "Software" },
    { value: "online-courses", label: "Online Courses" },
    { value: "subscriptions", label: "Subscriptions" },

    // Pets
    { value: "pet-supplies", label: "Pet Supplies" },
    { value: "dog-supplies", label: "Dog Supplies" },
    { value: "cat-supplies", label: "Cat Supplies" },
    { value: "aquarium", label: "Aquarium" },

    // Industrial
    { value: "industrial-scientific", label: "Industrial & Scientific" },
    { value: "lab-equipment", label: "Lab Equipment" },
    { value: "construction", label: "Construction Materials" },
    { value: "safety-equipment", label: "Safety Equipment" },

    // Miscellaneous
    { value: "gifts", label: "Gifts" },
    { value: "gift-cards", label: "Gift Cards" },
    { value: "handmade", label: "Handmade" },
    { value: "luxury", label: "Luxury" },
    { value: "clearance", label: "Clearance" }
];